version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/project-name-dev
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    volumes:
      - ./uploads:/app/uploads
    networks:
      - project-name-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=project-name-dev
    volumes:
      - mongo_data:/data/db
    networks:
      - project-name-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - project-name-network

volumes:
  mongo_data:
  redis_data:

networks:
  project-name-network:
    driver: bridge 